name: Pushing

on:
  push:
    branches: [main]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    environment: GitLab
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to NTNU GitLab Workspace
        env:
          TOKEN: ${{ secrets.GITLAB_TOKEN }}
          # for the first push, An owner token is needed.
        run:  |
          echo "Pushing to NTNU GitLab-Work-Space:"
          git fetch --unshallow "https://github.com/idarlm/prog2005-assignment1"
          git config user.name "Idar Løkset Mykløy"
          git config user.email "idarmy@stud.ntnu.no"
          git remote set-url origin "https://oauth2:$TOKEN@git.gvk.idi.ntnu.no/course/prog2005/prog2005-2023-workspace/idarmy/assignment-1.git"
          git push -u origin --all
          git push -u origin --tags
